### ISSUE TITLE
using gpu konduit. show some error

### ISSUE THREAD

**Issue by wangfeng-skymind** [KonduitAI/konduit-serving-examples#31]
Starting konduit server with an id of 'a37f71e6'
16:41:15.532 [main] INFO  ai.konduit.serving.util.LogUtils - Logging file at: /root/.konduit-serving/command_logs/a37f71e6.log
16:41:15.845 [main] INFO  a.k.s.l.KonduitServingLauncher - Setup micro meter options.
16:41:16.026 [vert.x-eventloop-thread-0] INFO  a.k.s.routers.PipelineRouteDefiner - Using metrics registry io.micrometer.prometheus.PrometheusMeterRegistry for inference
16:41:17.204 [vert.x-eventloop-thread-0] WARN  org.nd4j.linalg.factory.Nd4jBackend - Skipped [JCublasBackend] backend (unavailable): java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/konduit.jar/org/bytedeco/cuda/linux-x86_64/libjnicudart.so: libcudart.so.10.2: cannot open shared object file: No such file or directory
16:41:17.206 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable - java.lang.ExceptionInInitializerError
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at org.deeplearning4j.core.listener.HardwareMetric.fromSystem(HardwareMetric.java:130)
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.metrics.NativeMetrics.bindTo(NativeMetrics.java:60)
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.config.metrics.impl.MetricsBinderRendererAdapter.bindTo(MetricsBinderRendererAdapter.java:34)
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.routers.PipelineRouteDefiner.addMetric(PipelineRouteDefiner.java:755)
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.routers.PipelineRouteDefiner.defineRoutes(PipelineRouteDefiner.java:183)
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.verticles.inference.InferenceVerticle.setupWebServer(InferenceVerticle.java:87)
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.verticles.base.BaseRoutableVerticle.start(BaseRoutableVerticle.java:87)
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
16:41:17.207 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
16:41:17.208 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
16:41:17.208 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
16:41:17.208 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
16:41:17.208 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at java.lang.Thread.run(Thread.java:748)
16:41:17.208 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable - Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: https://deeplearning4j.konduit.ai/nd4j/backend
16:41:17.208 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5094)
16:41:17.208 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:270)
16:41:17.208 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    ... 17 more
16:41:17.208 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable - Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: https://deeplearning4j.konduit.ai/nd4j/backend
16:41:17.208 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:221)
16:41:17.208 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5091)
16:41:17.208 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    ... 18 more
16:41:17.209 [vert.x-eventloop-thread-1] ERROR i.v.c.i.l.c.VertxIsolatedDeployer - Failed in deploying verticle
java.lang.ExceptionInInitializerError: null
        at org.deeplearning4j.core.listener.HardwareMetric.fromSystem(HardwareMetric.java:130)
        at ai.konduit.serving.metrics.NativeMetrics.bindTo(NativeMetrics.java:60)
        at ai.konduit.serving.config.metrics.impl.MetricsBinderRendererAdapter.bindTo(MetricsBinderRendererAdapter.java:34)
        at ai.konduit.serving.routers.PipelineRouteDefiner.addMetric(PipelineRouteDefiner.java:755)
        at ai.konduit.serving.routers.PipelineRouteDefiner.defineRoutes(PipelineRouteDefiner.java:183)
        at ai.konduit.serving.verticles.inference.InferenceVerticle.setupWebServer(InferenceVerticle.java:87)
        at ai.konduit.serving.verticles.base.BaseRoutableVerticle.start(BaseRoutableVerticle.java:87)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: https://deeplearning4j.konduit.ai/nd4j/backend
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5094)
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:270)
        ... 17 common frames omitted
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: https://deeplearning4j.konduit.ai/nd4j/backend
        at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:221)

**Comment by wangfeng-skymind** [comment]
python3 build_jar.py --os linux-x86_64 --chip gpu --cuda-version 10.1
